### ISSUE TITLE
How to build using mingw32 on Linux?

### ISSUE THREAD

**Issue by Hacksawfred3232** [librsync/librsync#154]
Requesting this because I need rdiff as part of a requirement on a python lib I'm building. The API that my lib talks to requires a rsync signature file along with the main file or a rsync delta when uploading to their services. I only have a small server with about 3 GB of memory and a old processor, so I can't use WINE. Don't even know if cygwin works under wine and if anything that is built under cygwin can be ran on plain Windows.

**Comment by mosolovsa** [comment]
I'm not sure if this is what you want, but:

> cd ~/librsync-2.0.2

(directory with CMakeFile.txt located
>mkdir build
>cd build
>cmake -DMINGW=ON -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY -DCMAKE_C_COMPILER=i686-w64-mingw32.static-gcc ..

`-DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY` - to prevent compiling simple executable and trying to run it during cmake build.
i686-w64-mingw32.static-gcc must be path to your mingw c compiler.

>make rsync

Hope it helps...

**Comment by dbaarda** [comment]
With the merge of #161 a bunch of problems building with MinGW have been fixed. It should now be possible to build it using mingw32 and cmake without forcing a static library.

Please try it and let us know if there are any remaining problems or tricks to make it work. I welcome any pull requests with documentation to make this easier.

**Comment by Hacksawfred3232** [comment]
Sorry for not responding sooner! Trying to compile with mosolovsa's command minus the "STATIC_LIBRARY" flag returns this:
```
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/usr/bin/x86_64-w64-mingw32-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /opt/buildservice/SOURCE/librsync/CMakeFiles/CMakeTmp

    Run Build Command:"/usr/bin/make" "cmTC_1285f/fast"
    /usr/bin/make -f CMakeFiles/cmTC_1285f.dir/build.make CMakeFiles/cmTC_1285f.dir/build
    make[1]: Entering directory '/opt/buildservice/SOURCE/librsync/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_1285f.dir/testCCompiler.c.o
    /usr/bin/x86_64-w64-mingw32-gcc    -o CMakeFiles/cmTC_1285f.dir/testCCompiler.c.o   -c /opt/buildservice/SOURCE/librsync/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_1285f
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_1285f.dir/link.txt --verbose=1
    /usr/bin/x86_64-w64-mingw32-gcc      -rdynamic CMakeFiles/cmTC_1285f.dir/testCCompiler.c.o  -o cmTC_1285f
    x86_64-w64-mingw32-gcc: error: unrecognized command line option ‘-rdynamic’
    CMakeFiles/cmTC_1285f.dir/build.make:97: recipe for target 'cmTC_1285f' failed
    make[1]: *** [cmTC_1285f] Error 1
    make[1]: Leaving directory '/opt/buildservice/SOURCE/librsync/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_1285f/fast' failed
    make: *** [cmTC_1285f/fast] Error 2




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:19 (project)


-- Configuring incomplete, errors occurred!
See also "/opt/buildservice/SOURCE/librsync/CMakeFiles/CMakeOutput.log".
See also "/opt/buildservice/SOURCE/librsync/CMakeFiles/CMakeError.log".
```
(Oh and by the way, static-gcc does not exist on my system)

**Comment by deajan** [comment]
I also cannot build latest librsync 2.1.0 with mingw.

I need to build a static librsync lib using mingw, so I change CMakeLists.txt from 
```
add_library(rsync SHARED ${rsync_LIB_SRCS}
```
to
```
add_library(rsync STATIC ${rsync_LIB_SRCS}
```

This used to work with librsync 2.0.2 but does not anymore.

I've applied patch from #161  and tried again, I get the same following output:

```
-- Generating done
-- Build files have been written to: /opt/install/burp-cross-tools/depkgs/source/librsync-2.1.1
[  5%] Built target hashtable_test
[ 10%] Built target isprefix_test
[ 14%] Built target rabinkarp_test
[ 19%] Built target rollsum_test
[ 29%] Built target checksum_test
[ 49%] Built target sumset_test
[ 50%] Building C object CMakeFiles/rsync.dir/src/checksum.c.obj
/opt/install/burp-cross-tools/depkgs/source/librsync-2.1.1/src/checksum.c:28:27: error: variable 'RS_MD4_SUM_LENGTH' definition is marked dllimport
 LIBRSYNC_EXPORT const int RS_MD4_SUM_LENGTH = 16;
                           ^~~~~~~~~~~~~~~~~
/opt/install/burp-cross-tools/depkgs/source/librsync-2.1.1/src/checksum.c:28:27: warning: 'RS_MD4_SUM_LENGTH' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
/opt/install/burp-cross-tools/depkgs/source/librsync-2.1.1/src/checksum.c:29:27: error: variable 'RS_BLAKE2_SUM_LENGTH' definition is marked dllimport
 LIBRSYNC_EXPORT const int RS_BLAKE2_SUM_LENGTH = 32;
                           ^~~~~~~~~~~~~~~~~~~~
/opt/install/burp-cross-tools/depkgs/source/librsync-2.1.1/src/checksum.c:29:27: warning: 'RS_BLAKE2_SUM_LENGTH' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
make[2]: *** [CMakeFiles/rsync.dir/build.make:106: CMakeFiles/rsync.dir/src/checksum.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:322: CMakeFiles/rsync.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

I've also tried to build current git master, got the same results.
Does anyone have an idea what's changed so that static builds fail ?

Best regards.

**Comment by dbaarda** [comment]
To make librsync static compile you need to also add

target_compile_options(rsync PRIVATE -DLIBRSYNC_STATIC_DEFINE)

This ensures that LIBRSYNC_EXPORT is defined correctly for static linking in librsync_export.h.

However, I'd also like to figure out why dynamic linking is not working.

**Comment by deajan** [comment]
@dbaarda static compilation now works with the option you provided.
Btw, shared compilation works out of the box for me with current git master.
Maybe you could consider releasing librsync 2.1.1 soon, or at least an interim build with the mingw fixes applied ?

Thank you for your help.

**Comment by dbaarda** [comment]
Do we want to make static compilation a CMake configurable option? It looks like the way to do this is make BUILD_SHARED_LIBS an option and remove the explicit SHARED|STATIC from add_library();

https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html

We'd also need to conditionally set LIBRSYNC_STATIC_DEFINE if BUILD_SHARED_LIBS is OFF.

**Comment by dbaarda** [comment]
It's not entirely clear to me what is/isn't working with git master right now.

deajan: are you using mingw on windows, or cross-compiling to windows on linux? Could you give a quick ~5 line howto on what you are doing that works?

Hacksawfred3232: Is it still broken for you? The following seems to have good information on how to make mingw cross-compiling work with cmake;

https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/cross_compiling/Mingw

I'm happy to accept pull requests to make this easier, either by documenting it better, or improving our cmake configuration for that use-case.

I also have a pull request on the way to add BUILD_SHARED_LIBS as a cmake option for building librsync as a static library.

**Comment by dbaarda** [comment]
I also notice that Travis has grown support for windows compiles/tests;

https://docs.travis-ci.com/user/reference/windows/

I'd be very happy to accept pull requests that add travis tests for compiling on windows.

**Comment by deajan** [comment]
@dbaarda I'm cross compiling from a CentOS 8 box with mingw v7.3.0
I'll recompile tomorrow and will give you my howto (I use a separate toolchain file and also patch CMakeLists.txt in order to build static librsync and libtool libraries)

**Comment by dbaarda** [comment]
Note I've merged a pull that makes compiling static libs a cmake option, so you should be able to remove your CMakeLists.txt patch.

**Comment by dbaarda** [comment]
Also, I'm ready to release v2.2.0 (bump minor version because of added RabinKarp rollsum) as soon as you guys are happy with it.

**Comment by deajan** [comment]
Sorry being late for the party.

Here's my build recipe on howto cross compile librsync (current git master) as static library on Linux for Windows using mingw:

Using CentOS 8.0 with cmake 3.11.4 (but has previously worked with CentOS 7 too)

cmake command line
```
cmake -DBUILD_RDIFF=OFF -DCMAKE_INSTALL_PREFIX=/opt/install/burp-cross-tools/depkgs/mingw-w64-i686 -DCMAKE_PREFIX_PATH=/opt/install/burp-cross-tools/depkgs/mingw-w64-i686 -DCMAKE_INSTALL_LIBDIR=/opt/install/burp-cross-tools/depkgs/mingw-w64-i686/lib -DENABLE_COMPRESSION=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_DISABLE_FIND_PACKAGE_POPT=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_libb2=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_ZLIB=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_BZip2=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_Doxygen=TRUE -DCMAKE_TOOLCHAIN_FILE=/opt/librsync/toolchain.cmake
```

Cmake output
```
-- The C compiler identification is GNU 7.3.0
-- Check for working C compiler: /opt/install/burp-cross-tools/cross-tools/mingw-w64-i686/bin/i686-w64-mingw32-gcc
-- Check for working C compiler: /opt/install/burp-cross-tools/cross-tools/mingw-w64-i686/bin/i686-w64-mingw32-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- DO_RS_TRACE=0
-- Looking for include file alloca.h
-- Looking for include file alloca.h - not found
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - not found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file bzlib.h
-- Looking for include file bzlib.h - not found
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file malloc.h
-- Looking for include file malloc.h - found
-- Looking for include file mcheck.h
-- Looking for include file mcheck.h - not found
-- Looking for include file sys/file.h
-- Looking for include file sys/file.h - found
-- Looking for include file zlib.h
-- Looking for include file zlib.h - not found
-- Looking for alloca
-- Looking for alloca - not found
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for fseeko64
-- Looking for fseeko64 - found
-- Looking for _fseeki64
-- Looking for _fseeki64 - found
-- Looking for fstat64
-- Looking for fstat64 - not found
-- Looking for _fstati64
-- Looking for _fstati64 - found
-- Looking for fileno
-- Looking for fileno - found
-- Looking for _fileno
-- Looking for _fileno - found
-- Looking for memmove
-- Looking for memmove - found
-- Looking for memset
-- Looking for memset - found
-- Looking for strchr
-- Looking for strchr - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long
-- Check size of long - done
-- Check size of long long
-- Check size of long long - done
-- Check size of off_t
-- Check size of off_t - done
-- Check size of off64_t
-- Check size of off64_t - done
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned int
-- Check size of unsigned int - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Compiling to Win32 - printf "%zu" size_t formatting support disabled
-- Check if the system is big endian
-- Searching 16 bit integer
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- System is little-endian.
-- PROJECT_NAME  = librsync
-- BUILD_HOSTNAME = burpc8.netpower.local
-- CMAKE_SYSTEM = Windows
-- Using included blake2 implementation.
-- CMAKE_C_FLAGS  =  -Wall
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/librsync/librsync-2.2.0-git
```
Building
```
[root@burpc8 librsync-2.2.0-git]# make

Scanning dependencies of target hashtable_test
[  1%] Building C object CMakeFiles/hashtable_test.dir/tests/hashtable_test.c.obj
[  3%] Building C object CMakeFiles/hashtable_test.dir/src/hashtable.c.obj
[  5%] Linking C executable hashtable_test.exe
[  5%] Built target hashtable_test
Scanning dependencies of target isprefix_test
[  7%] Building C object CMakeFiles/isprefix_test.dir/tests/isprefix_test.c.obj
[  8%] Building C object CMakeFiles/isprefix_test.dir/src/isprefix.c.obj
[ 10%] Linking C executable isprefix_test.exe
[ 10%] Built target isprefix_test
Scanning dependencies of target rabinkarp_test
[ 12%] Building C object CMakeFiles/rabinkarp_test.dir/tests/rabinkarp_test.c.obj
[ 14%] Linking C executable rabinkarp_test.exe
[ 14%] Built target rabinkarp_test
Scanning dependencies of target rollsum_test
[ 15%] Building C object CMakeFiles/rollsum_test.dir/tests/rollsum_test.c.obj
[ 17%] Building C object CMakeFiles/rollsum_test.dir/src/rollsum.c.obj
[ 19%] Linking C executable rollsum_test.exe
[ 19%] Built target rollsum_test
Scanning dependencies of target checksum_test
[ 21%] Building C object CMakeFiles/checksum_test.dir/tests/checksum_test.c.obj
[ 22%] Building C object CMakeFiles/checksum_test.dir/src/checksum.c.obj
[ 24%] Building C object CMakeFiles/checksum_test.dir/src/rollsum.c.obj
[ 26%] Building C object CMakeFiles/checksum_test.dir/src/mdfour.c.obj
[ 28%] Building C object CMakeFiles/checksum_test.dir/src/blake2/blake2b-ref.c.obj
[ 29%] Linking C executable checksum_test.exe
[ 29%] Built target checksum_test
Scanning dependencies of target sumset_test
[ 31%] Building C object CMakeFiles/sumset_test.dir/tests/sumset_test.c.obj
[ 33%] Building C object CMakeFiles/sumset_test.dir/src/sumset.c.obj
[ 35%] Building C object CMakeFiles/sumset_test.dir/src/util.c.obj
[ 36%] Building C object CMakeFiles/sumset_test.dir/src/trace.c.obj
[ 38%] Building C object CMakeFiles/sumset_test.dir/src/hex.c.obj
[ 40%] Building C object CMakeFiles/sumset_test.dir/src/checksum.c.obj
[ 42%] Building C object CMakeFiles/sumset_test.dir/src/rollsum.c.obj
[ 43%] Building C object CMakeFiles/sumset_test.dir/src/mdfour.c.obj
[ 45%] Building C object CMakeFiles/sumset_test.dir/src/hashtable.c.obj
[ 47%] Building C object CMakeFiles/sumset_test.dir/src/blake2/blake2b-ref.c.obj
[ 49%] Linking C executable sumset_test.exe
[ 49%] Built target sumset_test
Scanning dependencies of target rsync
[ 50%] Building C object CMakeFiles/rsync.dir/src/prototab.c.obj
[ 52%] Building C object CMakeFiles/rsync.dir/src/base64.c.obj
[ 54%] Building C object CMakeFiles/rsync.dir/src/buf.c.obj
[ 56%] Building C object CMakeFiles/rsync.dir/src/checksum.c.obj
[ 57%] Building C object CMakeFiles/rsync.dir/src/command.c.obj
[ 59%] Building C object CMakeFiles/rsync.dir/src/delta.c.obj
[ 61%] Building C object CMakeFiles/rsync.dir/src/emit.c.obj
[ 63%] Building C object CMakeFiles/rsync.dir/src/fileutil.c.obj
[ 64%] Building C object CMakeFiles/rsync.dir/src/hashtable.c.obj
[ 66%] Building C object CMakeFiles/rsync.dir/src/hex.c.obj
[ 68%] Building C object CMakeFiles/rsync.dir/src/job.c.obj
[ 70%] Building C object CMakeFiles/rsync.dir/src/mdfour.c.obj
[ 71%] Building C object CMakeFiles/rsync.dir/src/mksum.c.obj
[ 73%] Building C object CMakeFiles/rsync.dir/src/msg.c.obj
[ 75%] Building C object CMakeFiles/rsync.dir/src/netint.c.obj
[ 77%] Building C object CMakeFiles/rsync.dir/src/patch.c.obj
[ 78%] Building C object CMakeFiles/rsync.dir/src/readsums.c.obj
[ 80%] Building C object CMakeFiles/rsync.dir/src/rollsum.c.obj
[ 82%] Building C object CMakeFiles/rsync.dir/src/scoop.c.obj
[ 84%] Building C object CMakeFiles/rsync.dir/src/stats.c.obj
[ 85%] Building C object CMakeFiles/rsync.dir/src/stream.c.obj
[ 87%] Building C object CMakeFiles/rsync.dir/src/sumset.c.obj
[ 89%] Building C object CMakeFiles/rsync.dir/src/trace.c.obj
[ 91%] Building C object CMakeFiles/rsync.dir/src/tube.c.obj
[ 92%] Building C object CMakeFiles/rsync.dir/src/util.c.obj
[ 94%] Building C object CMakeFiles/rsync.dir/src/version.c.obj
[ 96%] Building C object CMakeFiles/rsync.dir/src/whole.c.obj
[ 98%] Building C object CMakeFiles/rsync.dir/src/blake2/blake2b-ref.c.obj
[100%] Linking C shared library librsync.dll
[100%] Built target rsync
```

In order to achieve this, I use the following cmake Toolchain file (which is compatible with 32 and 64 bit versions of mingw):
```
# the name of the target operating system
SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE-SYSTEM_VERSION 1)

# Mingw architecture default is 64-bit
# To override:
#   $ export MINGW_ARCH=32
if(DEFINED ENV{MINGW_ARCH})
        set(MINGW_ARCH              "$ENV{MINGW_ARCH}")
else()
        set(MINGW_ARCH              "64")
endif()

if(${MINGW_ARCH} STREQUAL "32")
        set(CMAKE_SYSTEM_PROCESSOR  "i686")
elseif(${MINGW_ARCH} STREQUAL "64")
        set(CMAKE_SYSTEM_PROCESSOR  "x86_64")
else()
        message(FATAL_ERROR         "Unknown system architecture specified")
endif()

# Path to mingw
set(MINGW_PREFIX                    "/opt/install/burp-cross-tools/cross-tools/mingw-w64-i686")
# Linux mingw requires explicitly defined tools to prevent clash with native system tools
set(MINGW_TOOL_PREFIX               ${MINGW_PREFIX}/bin/i686-w64-mingw32-)

# Windows msys mingw ships with a mostly suitable preconfigured environment
if(DEFINED ENV{MSYSCON})
        set(CMAKE_GENERATOR         "MSYS Makefiles" CACHE STRING "" FORCE)
        set(MINGW_PREFIX            "/mingw${MINGW_ARCH}")
        set(MINGW_TOOL_PREFIX       "${MINGW_PREFIX}/bin/")

        # Msys compiler does not support @CMakeFiles/Include syntax
        set(CMAKE_C_USE_RESPONSE_FILE_FOR_INCLUDES   OFF)
        set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES OFF)
endif()

# The target environment
set(CMAKE_FIND_ROOT_PATH            ${MINGW_PREFIX})
set(CMAKE_INSTALL_PREFIX            ${MINGW_PREFIX})

# which compilers to use for C and C++
set(CMAKE_C_COMPILER                ${MINGW_TOOL_PREFIX}gcc)
set(CMAKE_CXX_COMPILER              ${MINGW_TOOL_PREFIX}g++)
set(CMAKE_RC_COMPILER               ${MINGW_TOOL_PREFIX}windres)

# adjust the default behaviour of the FIND_XXX() commands:
# search headers and libraries in the target environment, search
# programs in the host environment
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# Fix header finds
set(WASAPI_INCLUDE_DIR              ${MINGW_PREFIX}/include)

# Set release to be defaut
if(NOT CMAKE_BUILD_TYPE)
        set(CMAKE_BUILD_TYPE        "Release" CACHE STRING "Defaulting to Release build type for mingw")
endif()
```


I've also successfully build static rsync library ([100%] Linking C static library librsync.a) by adding `-DBUILD_SHARED_LIBS=OFF` to my cmake command line.

So far, for me, both static and dynamic libraries build well.

**Comment by dbaarda** [comment]
Do you think we should include a toolchain file in librsync? Or is this something developers using platforms that need one should already have, and we just need instructions and maybe a link to where you can get one?

**Comment by deajan** [comment]
IMO this is out of scope of librsync and relates more to the platform.
Maybe I can make a PR for this file as "mingw_cross_compile_toolchain.example" with a word in readme.md so.

**Comment by dbaarda** [comment]
Ok, thanks. In that case I think we can close this issue.

#171 is about adding the required documentation, and we'll use that issue to track getting docs added.

I'm closing this one now.
